services:
  - type: web
    name: resumeforge-ai
    runtime: python
    buildCommand: "sh ./build.sh"
    startCommand: "gunicorn resumeforge.wsgi:application --workers 3 --threads 2 --worker-class gthread --worker-connections 1000 --timeout 60"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.2
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: CELERY_TASK_ALWAYS_EAGER
        value: "True"
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: RAZORPAY_WEBHOOK_SECRET
        sync: false
