# Generated by Django 5.0.6 on 2026-08-31 03:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Role or job title (e.g. Senior Backend Engineer).', max_length=255)),
                ('raw_text', models.TextField(help_text='Full text of the job description or requirements.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_descriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Description',
                'verbose_name_plural': 'Job Descriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='PDF format only, maximum 5MB.', upload_to='resumes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('parsed_text', models.TextField(blank=True, help_text='Extracted plain text from the uploaded PDF resume.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('overall_score', models.IntegerField(blank=True, help_text='Overall match percentage (0-100).', null=True)),
                ('keyword_score', models.IntegerField(blank=True, help_text='Keyword relevance score (0-100).', null=True)),
                ('formatting_score', models.IntegerField(blank=True, help_text='Structure and ATS formatting compliance score (0-100).', null=True)),
                ('experience_score', models.IntegerField(blank=True, help_text='Experience and skills alignment score (0-100).', null=True)),
                ('missing_keywords', models.JSONField(blank=True, default=list, help_text='List of important keywords identified in JD but missing in Resume.')),
                ('suggestions', models.JSONField(blank=True, default=list, help_text='Actionable bullet points for improving the resume.')),
                ('error_message', models.TextField(blank=True, help_text='Error message if scan processing failed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='resumes.jobdescription')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='resumes.resume')),
            ],
            options={
                'verbose_name': 'Scan Result',
                'verbose_name_plural': 'Scan Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
