# Generated by Django 5.0.6 on 2026-09-10 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(help_text='PDF, DOCX, DOC, TXT, or RTF format, maximum 5MB.', upload_to='resumes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'txt', 'rtf', 'md'])]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='parsed_text',
            field=models.TextField(blank=True, help_text='Extracted plain text from the uploaded resume file.'),
        ),
    ]
