# Generated by Django 5.0.6 on 2026-08-31 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Production Key', help_text='Descriptive label for this API key.', max_length=100)),
                ('key', models.CharField(db_index=True, help_text='Secret API key token (rf_live_...).', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this API key is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Developer API Key',
                'verbose_name_plural': 'Developer API Keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
