# Generated by Django 5.0.6 on 2026-08-31 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(help_text='Target role (e.g. Senior Frontend Engineer, Product Manager).', max_length=255)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='in_progress', max_length=20)),
                ('summary', models.TextField(blank=True, help_text='Overall assessment, strengths, and areas for improvement upon completion.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(blank=True, help_text='Optional resume providing candidate background context.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_sessions', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview Session',
                'verbose_name_plural': 'Interview Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Question prompted by the AI interviewer.')),
                ('answer_text', models.TextField(blank=True, help_text="Candidate's submitted answer.", null=True)),
                ('ai_feedback', models.TextField(blank=True, help_text="Immediate feedback on candidate's answer.", null=True)),
                ('order', models.PositiveIntegerField(default=1, help_text='Sequential question number in session (1 through 6).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.interviewsession')),
            ],
            options={
                'verbose_name': 'Interview Question',
                'verbose_name_plural': 'Interview Questions',
                'ordering': ['order'],
                'unique_together': {('session', 'order')},
            },
        ),
    ]
